apiVersion: v1
kind: ConfigMap
metadata:
  name: showroom-configmap
  namespace: car-factory-dev
data:
  application.yaml: |+
    app:
      rest:
        factory:
          is-produce:
            url: https://factory:8080/factory/api/is-can-produce
            timeout: 5000
          assemble:
            url: https://factory:8080/factory/api/assemble
            timeout: 5000
      kafka:
        bootstrap-servers: 192.168.65.2:39092
        topics:
          is-ready: factory.is.ready
    spring:
      main:
        allow-bean-definition-overriding: true
      datasource:
        url: jdbc:mysql://192.168.65.2:3306/showroom
        username: root
        password: password
        driver-class-name: com.mysql.cj.jdbc.Driver
      jpa:
        open-in-view: false
        generate-ddl: false
        show-sql: false
